<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMHKkmq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMHKkmq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMHKkmq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMHKkmq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTMHKkmq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TMHKkmq',
    'container.build_id' => 'be9b4934',
    'container.build_time' => 1559807395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMHKkmq');
