<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container965XdQE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container965XdQE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container965XdQE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container965XdQE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container965XdQE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '965XdQE',
    'container.build_id' => '5e5e703e',
    'container.build_time' => 1559309982,
], __DIR__.\DIRECTORY_SEPARATOR.'Container965XdQE');
