<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtUrx2f\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtUrx2f/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLtUrx2f.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLtUrx2f\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLtUrx2f\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LtUrx2f',
    'container.build_id' => '0fb220fc',
    'container.build_time' => 1559774778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtUrx2f');
