# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# fos_rest: ~
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
fos_rest:
    routing_loader:
        include_format: false
    zone:
        - { path: ^/api/* }
    view:
        view_response_listener:  true
    #La seule règle déclarée dit que pour toutes les URL (path: ^/api), 
    #le format prioritaire est le JSON (priorities: ['json']) 
    #et si aucun format n’est demandé par le client, 
    #il faudra utiliser le JSON quand même (fallback_format: 'json').
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }