#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_signin:
    path: /api/signin

api_signup:
    path: /api/signup

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
