<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XWmKAY6' shared service.

return $this->privates['.service_locator.XWmKAY6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'gamerepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService.php', true],
]);
